server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: 123456
    virtual-host: /leyou
ly:
  sms:
    accessKeyId: LTAITrriZ39qedCO # 你自己的accessKeyId
    accessKeySecret: M24pSWmODzRMnd5mS4OUqeQ7wvltl1 # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称