server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
      host: 127.0.0.1
      username: leyou
      password: 123456
      virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  page:
    destPath: D:\develop\nginx-1.12.2\html\123
